CREATE TABLE "adjacency_rules" (
"rule_id" INTEGER,
  "room_a" TEXT,
  "room_b" TEXT,
  "relationship" TEXT,
  "reason_code" TEXT,
  "reason_text" TEXT,
  "bhk_applicability" TEXT,
  "priority" INTEGER,
  "door_required" INTEGER,
  "door_width_m" REAL,
  "min_shared_wall_m" REAL,
  "facing_dependency" TEXT,
  "vastu_compliance" INTEGER,
  "nbc_section" TEXT
);
CREATE TABLE "baker_principles" (
"principle_id" INTEGER,
  "principle_name" TEXT,
  "category" TEXT,
  "description" TEXT,
  "application_condition" TEXT,
  "plot_area_min_sqm" REAL,
  "plot_area_max_sqm" REAL,
  "climate_zones" TEXT,
  "applicable_rooms" TEXT,
  "wall_thickness_mm" REAL,
  "cost_saving_pct" REAL,
  "material_saving_pct" REAL,
  "thermal_benefit" TEXT,
  "implementation_detail" TEXT,
  "nbc_compliant" INTEGER,
  "tncdbr_compliant" INTEGER,
  "tn_districts_applicable" TEXT,
  "reference_source" TEXT,
  "drawing_impact" TEXT
);
CREATE TABLE "circulation_zones" (
"zone_id" INTEGER,
  "zone_name" TEXT,
  "rooms_in_zone" TEXT,
  "zone_description" TEXT,
  "bhk_applicability" TEXT,
  "facing_dependency" TEXT,
  "must_be_accessible_from" TEXT,
  "must_not_be_accessible_from" TEXT,
  "max_depth_from_entry" INTEGER,
  "min_zone_width_m" REAL,
  "recommended_zone_fraction" REAL,
  "vastu_zone_name" TEXT,
  "cross_ventilation_required" INTEGER,
  "natural_light_required" INTEGER,
  "noise_sensitivity" TEXT,
  "privacy_penetration_rule" TEXT,
  "drawing_color_hint" TEXT,
  "typical_tn_arrangement" TEXT
);
CREATE TABLE "climate_data" (
"record_id" INTEGER,
  "district" TEXT,
  "climate_zone" TEXT,
  "avg_temp_summer_c" REAL,
  "avg_temp_winter_c" REAL,
  "avg_temp_annual_c" REAL,
  "max_temp_c" REAL,
  "min_temp_c" REAL,
  "annual_rainfall_mm" INTEGER,
  "monsoon_months" TEXT,
  "relative_humidity_summer_pct" REAL,
  "relative_humidity_winter_pct" REAL,
  "prevailing_wind_direction" TEXT,
  "prevailing_wind_speed_kmh" REAL,
  "solar_radiation_kwh_m2_day" REAL,
  "latitude_degrees" REAL,
  "longitude_degrees" REAL,
  "ecbc_climate_zone" TEXT,
  "optimal_plot_facing" TEXT,
  "window_north_score" REAL,
  "window_south_score" REAL,
  "window_east_score" REAL,
  "window_west_score" REAL,
  "recommended_overhang_depth_m" REAL,
  "wall_thickness_recommendation_mm" INTEGER,
  "roof_type_recommendation" TEXT,
  "cross_ventilation_priority" TEXT,
  "courtyard_benefit" TEXT,
  "passive_strategy_1" TEXT,
  "passive_strategy_2" TEXT,
  "passive_strategy_3" TEXT,
  "window_to_wall_ratio_recommended" REAL,
  "floor_plan_orientation_rule" TEXT,
  "imd_reference" TEXT
);
CREATE TABLE "entry_sequence_rules" (
"seq_id" INTEGER,
  "sequence_step" INTEGER,
  "space_name" TEXT,
  "space_type" TEXT,
  "is_mandatory" INTEGER,
  "is_optional" INTEGER,
  "min_depth_m" REAL,
  "typical_depth_m" REAL,
  "width_relationship" TEXT,
  "visual_termination" TEXT,
  "privacy_transition" TEXT,
  "transition_element" TEXT,
  "facing_n_description" TEXT,
  "facing_s_description" TEXT,
  "facing_e_description" TEXT,
  "facing_w_description" TEXT,
  "vastu_significance" TEXT,
  "traditional_tn_element" TEXT,
  "modern_adaptation" TEXT,
  "drawing_annotation" TEXT,
  "bhk_applicability" TEXT,
  "plot_area_min_sqm" REAL
);
CREATE TABLE "materials_db" (
"material_id" INTEGER,
  "material_name" TEXT,
  "material_category" TEXT,
  "subcategory" TEXT,
  "application" TEXT,
  "unit" TEXT,
  "cost_per_unit_inr_low" REAL,
  "cost_per_unit_inr_high" REAL,
  "cost_per_unit_inr_avg" REAL,
  "districts_available" TEXT,
  "districts_expensive" TEXT,
  "thermal_performance" TEXT,
  "climate_zone_suitability" TEXT,
  "sustainability_rating" INTEGER,
  "baker_recommended" INTEGER,
  "local_availability" TEXT,
  "carbon_footprint" TEXT,
  "skill_level_required" TEXT,
  "typical_thickness_mm" REAL,
  "compressive_strength_mpa" REAL,
  "thermal_conductivity_w_mk" REAL,
  "water_resistance" TEXT,
  "maintenance_frequency" TEXT,
  "lifespan_years" INTEGER,
  "nbc_approved" INTEGER,
  "is_load_bearing" REAL,
  "wall_drawing_color_hex" TEXT,
  "hatch_pattern" TEXT,
  "notes" TEXT
);
CREATE TABLE "movement_paths" (
"path_id" INTEGER,
  "from_space" TEXT,
  "to_space" TEXT,
  "path_type" TEXT,
  "movement_direction" TEXT,
  "min_passage_width_m" REAL,
  "max_hops_from_entrance" REAL,
  "privacy_level" TEXT,
  "bhk_applicability" TEXT,
  "facing_dependency" TEXT,
  "reason" TEXT,
  "nbc_reference" TEXT,
  "vastu_basis" INTEGER,
  "violation_consequence" TEXT,
  "graph_edge_weight" REAL,
  "is_critical_path" INTEGER
);
CREATE TABLE "nbc_codes" (
"code_id" INTEGER,
  "nbc_section" TEXT,
  "code_category" TEXT,
  "room_type" TEXT,
  "parameter_name" TEXT,
  "min_value" REAL,
  "max_value" REAL,
  "unit" TEXT,
  "occupancy_type" TEXT,
  "bhk_applicability" TEXT,
  "condition" TEXT,
  "enforcement_level" TEXT,
  "penalty_for_violation" TEXT,
  "drawing_requirement" TEXT,
  "compliance_check" TEXT,
  "common_violation" TEXT,
  "waiver_possible" INTEGER,
  "tn_local_amendment" TEXT
);
CREATE TABLE "passage_dimensions" (
"dim_id" INTEGER,
  "passage_type" TEXT,
  "min_clear_width_m" REAL,
  "recommended_width_m" REAL,
  "max_width_m" REAL,
  "min_height_m" REAL,
  "recommended_height_m" REAL,
  "door_type" TEXT,
  "door_swing_clearance_m" REAL,
  "bhk_applicability" TEXT,
  "nbc_reference" TEXT,
  "applies_to_floors" TEXT,
  "accessibility_compliant" INTEGER,
  "drawing_symbol" TEXT,
  "dimension_annotation" TEXT,
  "common_tn_practice" TEXT
);
CREATE TABLE "plot_configurations" (
"config_id" INTEGER,
  "plot_name" TEXT,
  "plot_width_m" REAL,
  "plot_depth_m" REAL,
  "plot_area_sqm" REAL,
  "plot_area_cents" REAL,
  "plot_area_sqft" REAL,
  "facing" TEXT,
  "bhk_type" TEXT,
  "is_suitable" INTEGER,
  "suitability_reason" TEXT,
  "net_buildable_area_sqm" REAL,
  "net_buildable_width_m" REAL,
  "net_buildable_depth_m" REAL,
  "zone_public_pct" INTEGER,
  "zone_private_pct" INTEGER,
  "zone_service_pct" INTEGER,
  "master_bedroom_target_w" REAL,
  "master_bedroom_target_d" REAL,
  "bedroom2_target_w" REAL,
  "bedroom2_target_d" REAL,
  "bedroom3_target_w" REAL,
  "bedroom3_target_d" REAL,
  "living_target_w" REAL,
  "living_target_d" REAL,
  "dining_target_w" REAL,
  "dining_target_d" REAL,
  "kitchen_target_w" REAL,
  "kitchen_target_d" REAL,
  "toilet_att_target_w" REAL,
  "toilet_att_target_d" REAL,
  "toilet_common_target_w" REAL,
  "toilet_common_target_d" REAL,
  "utility_target_w" REAL,
  "utility_target_d" REAL,
  "verandah_target_w" REAL,
  "verandah_target_d" REAL,
  "pooja_room_possible" INTEGER,
  "staircase_possible" INTEGER,
  "courtyard_possible" INTEGER,
  "common_in_district" TEXT,
  "vastu_front_facing" TEXT,
  "layout_strategy" TEXT,
  "typical_use" TEXT,
  "road_width_typical_m" REAL,
  "fsi_applicable" REAL,
  "is_corner_plot" INTEGER,
  "special_notes" TEXT
);
CREATE TABLE "tn_setbacks" (
"rule_id" INTEGER,
  "authority_type" TEXT,
  "district" TEXT,
  "plot_area_min_sqm" INTEGER,
  "plot_area_max_sqm" REAL,
  "road_width_min_m" REAL,
  "road_width_max_m" REAL,
  "front_setback_m" REAL,
  "rear_setback_m" REAL,
  "side_setback_left_m" REAL,
  "side_setback_right_m" REAL,
  "max_height_m" INTEGER,
  "max_floors" INTEGER,
  "fsi" REAL,
  "max_ground_coverage_pct" INTEGER,
  "setback_for_facing_n" INTEGER,
  "setback_for_facing_s" INTEGER,
  "setback_for_facing_e" INTEGER,
  "setback_for_facing_w" INTEGER,
  "compound_wall_height_max_m" REAL,
  "parking_requirement" TEXT,
  "annotation_text" TEXT,
  "regulation_reference" TEXT,
  "effective_date" TEXT,
  "special_condition" TEXT
);
CREATE INDEX idx_adj_room_a ON adjacency_rules(room_a);
CREATE INDEX idx_adj_room_b ON adjacency_rules(room_b);
CREATE INDEX idx_adj_priority ON adjacency_rules(priority);
CREATE INDEX idx_path_from ON movement_paths(from_space);
CREATE INDEX idx_path_to ON movement_paths(to_space);
CREATE INDEX idx_path_critical ON movement_paths(is_critical_path);
CREATE INDEX idx_climate_district ON climate_data(district);
CREATE INDEX idx_nbc_category ON nbc_codes(code_category);
CREATE INDEX idx_nbc_room ON nbc_codes(room_type);
CREATE INDEX idx_mat_category ON materials_db(material_category);
CREATE INDEX idx_mat_baker ON materials_db(baker_recommended);
CREATE INDEX idx_plot_area ON plot_configurations(plot_area_sqm);
CREATE INDEX idx_plot_bhk ON plot_configurations(bhk_type);
CREATE INDEX idx_plot_facing ON plot_configurations(facing);
CREATE INDEX idx_zone_name ON circulation_zones(zone_name);
CREATE INDEX idx_entry_step ON entry_sequence_rules(sequence_step);
CREATE INDEX idx_setback_district ON tn_setbacks(district);
CREATE INDEX idx_setback_area_min ON tn_setbacks(plot_area_min_sqm);
CREATE INDEX idx_passage_type ON passage_dimensions(passage_type);
CREATE INDEX idx_baker_cat ON baker_principles(category);
